[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# OpenZeppelin Foundry Upgrades
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

evm_version = "cancun"

# solc
solc_version = '0.8.19'

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
